\ProvidesClass{standard}
\LoadClass{article}

\topmargin=-0.3in
\textheight=9.2in
\textwidth=168mm
\oddsidemargin=-0.2in
\evensidemargin=-0.2in

\newcommand{\find}{\leavevmode{\parindent=1em\indent}}
\usepackage[utf8]{inputenc}
% \newif\ifquoteopen
% \catcode`\"=\active % lets you define `"` as a macro
% \DeclareRobustCommand*{"}{%
%    \ifquoteopen
%      \quoteopenfalse "%
%    \else
%      \quoteopentrue ``%
%    \fi
% }
